api:
  dashboard: true
  insecure: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

global:
  sendAnonymousUsage: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: app_app-network
  file:
    directory: "/config"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: herdeybayor4real@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: http

log:
  level: INFO
  format: json

accessLog:
  format: json

