---
- name: Restart Docker Compose services
  community.docker.docker_compose_v2:
    project_src: "{{ app_directory }}"
    state: present
  become_user: ubuntu

- name: Reload systemd
  systemd:
    daemon_reload: yes

